import pkg from 'pg';
const { Client } = pkg;

const connectionString = "postgresql://postgres:f8%23mK9%21zP2%40q5vR_9x@db.pxvqxcbqfxpeashgnvjx.supabase.co:5432/postgres";

async function setupMemosDB() {
  const client = new Client({ connectionString });
  try {
    await client.connect();
    
    const query = `
      CREATE TABLE IF NOT EXISTS public.memos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        content TEXT DEFAULT '',
        updated_by TEXT,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      ALTER TABLE public.memos ENABLE ROW LEVEL SECURITY;

      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.memos;
      CREATE POLICY "誰でも読み書き可能" ON public.memos FOR ALL USING (true);
      
      -- 初期データ（共有メモ1件）
      INSERT INTO public.memos (id, content) VALUES (1, 'チーム共有のメモ帳です。自由に書き込んでください！') 
      ON CONFLICT (id) DO NOTHING;
    `;
    
    await client.query(query);
    console.log("Memos table created successfully!");
  } catch(e) {
    console.error("DB Setup Error (memos):", e);
  } finally {
    await client.end();
  }
}
setupMemosDB();
