import pkg from 'pg';
const { Client } = pkg;

const connectionString = "postgresql://postgres:f8%23mK9%21zP2%40q5vR_9x@db.pxvqxcbqfxpeashgnvjx.supabase.co:5432/postgres";

async function setup() {
  const client = new Client({ connectionString });

  try {
    await client.connect();
    console.log("Connected to Supabase PostgreSQL.");

    const query = `
      -- messages テーブルの作成
      CREATE TABLE IF NOT EXISTS public.messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        text TEXT,
        image_url TEXT,
        user_id TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      -- 誰でも読み書きできるようにする設定 (RLS disable or enable policy)
      ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
      
      -- 既存ポリシーがあれば削除し、新しいものを設定 (エラー回避のため)
      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.messages;
      CREATE POLICY "誰でも読み書き可能" ON public.messages FOR ALL USING (true);

      -- chat_media バケットが存在しなければ作成
      INSERT INTO storage.buckets (id, name, public) 
      VALUES ('chat_media', 'chat_media', true)
      ON CONFLICT (id) DO NOTHING;

      -- 全員アップロード可能なポリシーを設定
      DROP POLICY IF EXISTS "Anyone can upload media" ON storage.objects;
      CREATE POLICY "Anyone can upload media" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'chat_media');
      
      DROP POLICY IF EXISTS "Anyone can view media" ON storage.objects;
      CREATE POLICY "Anyone can view media" ON storage.objects FOR SELECT TO public USING (bucket_id = 'chat_media');
    `;

    await client.query(query);
    console.log("Database tables, policies, and storage buckets created successfully!");
  } catch (err) {
    console.error("Error setting up database:", err);
  } finally {
    await client.end();
  }
}

setup();
