import pkg from 'pg';
const { Client } = pkg;

const connectionString = "postgresql://postgres:f8%23mK9%21zP2%40q5vR_9x@db.pxvqxcbqfxpeashgnvjx.supabase.co:5432/postgres";

async function setup() {
  const client = new Client({ connectionString });

  try {
    await client.connect();
    console.log("Connected to Supabase PostgreSQL.");

    const query = `
      -- ユーザープロファイル（長期記憶 Layer 1）
      CREATE TABLE IF NOT EXISTS public.mochi_user_profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        facts JSONB DEFAULT '[]'::jsonb,
        personality TEXT,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
      );

      ALTER TABLE public.mochi_user_profiles ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.mochi_user_profiles;
      CREATE POLICY "誰でも読み書き可能" ON public.mochi_user_profiles FOR ALL USING (true);

      -- 初期データ
      INSERT INTO public.mochi_user_profiles (user_id, display_name, facts, personality)
      VALUES
        ('user_a', 'ミルク', '[]'::jsonb, NULL),
        ('user_b', 'メリー', '[]'::jsonb, NULL)
      ON CONFLICT (user_id) DO NOTHING;

      -- 2人の関係性ステート
      CREATE TABLE IF NOT EXISTS public.mochi_relationship (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        vibe TEXT DEFAULT 'normal',
        vibe_reason TEXT,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
      );

      ALTER TABLE public.mochi_relationship ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.mochi_relationship;
      CREATE POLICY "誰でも読み書き可能" ON public.mochi_relationship FOR ALL USING (true);

      -- 初期データ
      INSERT INTO public.mochi_relationship (vibe, vibe_reason)
      SELECT 'normal', '初期状態'
      WHERE NOT EXISTS (SELECT 1 FROM public.mochi_relationship);

      -- 会話サマリー（中期記憶 Layer 2）
      CREATE TABLE IF NOT EXISTS public.mochi_conversation_summaries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        summary TEXT NOT NULL,
        messages_from BIGINT NOT NULL,
        messages_to BIGINT NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
      );

      ALTER TABLE public.mochi_conversation_summaries ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "誰でも読み書き可���" ON public.mochi_conversation_summaries;
      CREATE POLICY "誰でも読み書き可能" ON public.mochi_conversation_summaries FOR ALL USING (true);

      -- メモリ操作ログ（デ��ッグ用）
      CREATE TABLE IF NOT EXISTS public.mochi_memory_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        action TEXT NOT NULL,
        detail JSONB,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
      );

      ALTER TABLE public.mochi_memory_log ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.mochi_memory_log;
      CREATE POLICY "誰でも読み書き可能" ON public.mochi_memory_log FOR ALL USING (true);
    `;

    await client.query(query);
    console.log("Mochi memory tables created successfully!");
    console.log("  - mochi_user_profiles (Layer 1: 長期記憶)");
    console.log("  - mochi_relationship (関係性Vibe)");
    console.log("  - mochi_conversation_summaries (Layer 2: 中��記憶)");
    console.log("  - mochi_memory_log (デバッグログ)");
  } catch (err) {
    console.error("Error setting up database:", err);
  } finally {
    await client.end();
  }
}

setup();
