import webPush from 'web-push';
import fs from 'fs';
import pkg from 'pg';
const { Client } = pkg;

// 生成したVAPIDキーを .env.local へ追記
const vapidKeys = webPush.generateVAPIDKeys();
const envAdditions = `\n# Web Push VAPID Keys
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${vapidKeys.publicKey}
VAPID_PRIVATE_KEY=${vapidKeys.privateKey}
VAPID_SUBJECT=mailto:vibe_admin@example.com
`;

fs.appendFileSync('.env.local', envAdditions);
console.log("VAPID Keys generated and appended to .env.local.");

// Supabaseに購読管理テーブル (subscriptions) を作成
const connectionString = "postgresql://postgres:f8%23mK9%21zP2%40q5vR_9x@db.pxvqxcbqfxpeashgnvjx.supabase.co:5432/postgres";

async function setupDB() {
  const client = new Client({ connectionString });
  try {
    await client.connect();
    
    // WebPushで使うブラウザエンドポイントとキー情報(p256dh, auth)を保持
    const query = `
      CREATE TABLE IF NOT EXISTS public.subscriptions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        endpoint TEXT UNIQUE NOT NULL,
        p256dh TEXT NOT NULL,
        auth TEXT NOT NULL,
        user_id TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
      );

      ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

      DROP POLICY IF EXISTS "誰でも読み書き可能" ON public.subscriptions;
      CREATE POLICY "誰でも読み書き可能" ON public.subscriptions FOR ALL USING (true);
    `;
    
    await client.query(query);
    console.log("Subscriptions table created successfully!");
  } catch(e) {
    console.error("DB Setup Error (web push table):", e);
  } finally {
    await client.end();
  }
}
setupDB();
